services:
    mysqldb:
        image: mysql:latest
        container_name: tododatabasecontainer
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            DB_PORT: 3306
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: todo
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
        networks:
            - internalnet
    nodeapp:
        container_name: todoapicontainer
        build: .
        image: todoapi:1.0
        ports:
            - "8080:8080"
        expose:
            - "8080"
        environment:
            DB_HOST: mysqldb
            DB_USER: "admin"
            DB_PASSWORD: "password"
            DB_NAME: "todo"
            DB_PORT: "3306"
        depends_on:
            - mysqldb
        networks:
            - internalnet

networks:
    internalnet:
        driver: bridge
